---
title: "EDA"
output: github_document
date: "2025-10-02"
---

```{r}
library(tidyverse)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

import the weather data
note: `mutate(month = floor_date(date, unit = "month"))` = creates a new variable called `month` and variable is a rounded version of the `date` variable.
```{r}
data("weather_df")

weather_df = weather_df %>% 
  mutate(month = floor_date(date, unit = "month"))
```

```{r}
weather_df %>% 
  ggplot(aes(x = prcp)) +
  geom_histogram()
```

check on extreme values - you can even research why you are seeing those values on google
```{r}
weather_df %>% 
  filter(prcp > 1000)
```

look at data again
```{r}
weather_df %>% 
  filter(tmax >= 20, tmax <= 30) %>% 
  ggplot(aes(x = tmin, y = tmax), color = name, shape = name) +
  geom_point()
```

```{r}
weather_df %>% 
  group_by(month)
```

group and count things
```{r}
weather_df %>% 
  group_by(name) %>% 
  summarize(
    n = n()
  )
```

```{r}
weather_df %>% 
  group_by(month) %>% 
  summarize(
    n = n()
  )
```


```{r}
weather_df %>% 
  group_by(month) %>% 
  summarize(
    n = n_distinct(date)
  )
```


you can count directly
```{r}
weather_df %>% 
  count(name)
```

```{r}
weather_df %>% 
  group_by(month) %>% 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),
    median_min = median(tmin, na.rm = TRUE),
    sd_prcp = sd(prcp, na.rm = TRUE)
  )
```

