---
title: "tidy_data"
output: github_document
date: "2025-09-23"
---

```{r}
library(tidyverse)
library(readxl)
library(haven)
```


This document will show how to tidy data.


## Pivot longer

```{r}
pups_df = 
  read_csv("p8105/lecture_code/data_import_examples/FAS_pups.csv") %>% 
  janitor::clean_names() %>% 
    pivot_longer(
    cols = bdi_score_bl:bdi_score_12m,
    names_to = "visti",
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
    ) %>% 
  mutate (visit = replace(visit, visit = "bl", "00m")) %>% 
  relocate(id, visit)
```

```{r}
litters_df = 
  read_csv("p8105/lecture_code/data_import_examples/FAS_litters.csv", na = c("NA", ".", " ")) %>% 
  janitor::clean_names() %>% 
  pivot_longer (
  cols = gd0_weight:gd18_weight,
  names_to ="gd_time",
  values_to = "weight"
  ) %>% 
  mutate(gd_time = case_math(
    gd_time, 
    "gd0_weight" ~ 0,
    "gd18weight" ~ 18
  ))
```

## Pivot wider

let's make up an analysis result table

```{r}
analysis_df = 
  tibble(group = c("treatment", "treatment", "control", "control"),
         time = c("pre", "post", "pre", "post"),
         mean = c(4, 10, 4.2, 5))
```

pivot wider for human readibility
```{r}
analysis_df %>% 
  pivot_wider(
    names_from = time,
    values_from = mean
  ) %>% 
  knitr::kable()
```


## Bind tables
note: if you want to stack tables together

```{r}
fellowship_ring = 
  read_excel("p8105/lecture_code/data_import_examples/LotR.Words.xslx", range = "B3:D6") %>% 
  mutate = (movie = "fellowship_ring")

two_towers = 
  read_excel("p8105/lecture_code/data_import_examples/LotR.Words.xslx", range = "F3:H6") %>% 
  mutate = (movie = "two_towers")

return_king = 
  read_excel("p8105/lecture_code/data_import_examples/LotR.Words.xslx", range = "J3:L6") %>% 
  mutate = (movie = "return_king")

lotr_df = 
  bind_rows(fellowship_riing, two_towers, return_king) %>% 
  janitor::clean_name() %>% 
  pivot_longer(
    cols = female:male,
    names_to = "sex",
    values_to = "words" 
    ) %>% 
    relocate(movie) %>% 
    mutate(race = str_to_lower(race))
```

## Join FAS datasets
note: joining two tables by unique id

import `litters` dataset
```{r}
litters_df = 
  read_csv("p8105/lecture_code/data_import_examples/FAS_litters.csv", na = c("NA", ".", " ")) %>%
  janitor::clean_names() %>% 
  mutate(wt_gain = gd18_weight - gd0_weight) %>% 
  separate(
    group, into = c("doese", "day_of_treatment"")
  )
```

```{r}
pups_df = 
  read_csv("p8105/lecture_code/data_import_examples/FAS_pups.csv", na = c("NA", ".", " ")) %>%
  janitor::clean_names() %>% 
  mutate(sex = case_match(
    sex,
    1 ~ "male",
    2 ~ "female"
  )
  )
```

join the datasets!
```{r}
fas_df = 
  lef_join(pups_df, litters_df, by = "litter_number") %>% 
  relocate(litter_number, dose, df, day_of_treatment)
```

